// https://restcountries.com/v3.1/region/asia

// get whole object
// const OBJ = JSON.parse(document.body.innerText).reduce((acc, cur) => {
//   acc[cur.flags || cur.flags.png] = cur.name.common;
//   return acc;
// }, {});

// get name list
// const LIST = JSON.parse(document.body.innerText)
//   .map((c) => c.name.common)
//   .sort();

// reverse object:
// const reverseObj = (obj) => Object.fromEntries(Object.entries(obj).map((e) => [e[1], e[0]]));

const QA = {
  'cy': 'Cyprus',
  'mk': 'North Macedonia',
  'ye': 'Yemen',
  'sx': 'Sint Maarten',
  'mo': 'Macau',
  'ng': 'Nigeria',
  'so': 'Somalia',
  'mm': 'Myanmar',
  'lr': 'Liberia',
  'dm': 'Dominica',
  'kn': 'Saint Kitts and Nevis',
  'kp': 'North Korea',
  'sa': 'Saudi Arabia',
  'np': 'Nepal',
  've': 'Venezuela',
  'gu': 'Guam',
  'bm': 'Bermuda',
  'ke': 'Kenya',
  'cm': 'Cameroon',
  'rw': 'Rwanda',
  'mr': 'Mauritania',
  'nc': 'New Caledonia',
  'fj': 'Fiji',
  'ar': 'Argentina',
  'bn': 'Brunei',
  'ni': 'Nicaragua',
  'gb': 'United Kingdom',
  'la': 'Laos',
  'mh': 'Marshall Islands',
  'ua': 'Ukraine',
  'im': 'Isle of Man',
  'kw': 'Kuwait',
  'ag': 'Antigua and Barbuda',
  'nl': 'Netherlands',
  'pw': 'Palau',
  'nz': 'New Zealand',
  'cg': 'Republic of the Congo',
  'vg': 'British Virgin Islands',
  'bh': 'Bahrain',
  'bo': 'Bolivia',
  'tg': 'Togo',
  'uz': 'Uzbekistan',
  'bs': 'Bahamas',
  'mv': 'Maldives',
  'tm': 'Turkmenistan',
  'uy': 'Uruguay',
  'bg': 'Bulgaria',
  'ls': 'Lesotho',
  'pm': 'Saint Pierre and Miquelon',
  'cu': 'Cuba',
  'ht': 'Haiti',
  'mt': 'Malta',
  'to': 'Tonga',
  'fk': 'Falkland Islands',
  'et': 'Ethiopia',
  'ss': 'South Sudan',
  'tn': 'Tunisia',
  'pr': 'Puerto Rico',
  'ec': 'Ecuador',
  'cv': 'Cape Verde',
  'mc': 'Monaco',
  'tj': 'Tajikistan',
  'bw': 'Botswana',
  'bv': 'Bouvet Island',
  'id': 'Indonesia',
  'ee': 'Estonia',
  'qa': 'Qatar',
  'ky': 'Cayman Islands',
  'hr': 'Croatia',
  'zm': 'Zambia',
  'gp': 'Guadeloupe',
  'ro': 'Romania',
  'fo': 'Faroe Islands',
  'md': 'Moldova',
  'nu': 'Niue',
  'wf': 'Wallis and Futuna',
  'pn': 'Pitcairn Islands',
  'bb': 'Barbados',
  'ba': 'Bosnia and Herzegovina',
  'kr': 'South Korea',
  'bf': 'Burkina Faso',
  'sv': 'El Salvador',
  'sy': 'Syria',
  'co': 'Colombia',
  'bd': 'Bangladesh',
  'mq': 'Martinique',
  'fm': 'Micronesia',
  'se': 'Sweden',
  'hu': 'Hungary',
  'tf': 'French Southern and Antarctic Lands',
  'nr': 'Nauru',
  'iq': 'Iraq',
  'pl': 'Poland',
  'ne': 'Niger',
  'gr': 'Greece',
  'tz': 'Tanzania',
  'ma': 'Morocco',
  'li': 'Liechtenstein',
  'tl': 'Timor-Leste',
  'er': 'Eritrea',
  'yt': 'Mayotte',
  'fr': 'France',
  'hn': 'Honduras',
  'ws': 'Samoa',
  'gl': 'Greenland',
  'xk': 'Kosovo',
  'ai': 'Anguilla',
  'rs': 'Serbia',
  'sk': 'Slovakia',
  'hm': 'Heard Island and McDonald Islands',
  'ki': 'Kiribati',
  'ms': 'Montserrat',
  'es': 'Spain',
  'bz': 'Belize',
  'sc': 'Seychelles',
  'eh': 'Western Sahara',
  'gi': 'Gibraltar',
  'th': 'Thailand',
  'vn': 'Vietnam',
  // 'sh': 'Saint Helena, Ascension and Tristan da Cunha',
  'sh': 'Saint Helena',
  'at': 'Austria',
  'vc': 'Saint Vincent and the Grenadines',
  'ad': 'Andorra',
  // 'sj': 'Svalbard and Jan Mayen', norway flag
  'nf': 'Norfolk Island',
  'sr': 'Suriname',
  'mn': 'Mongolia',
  'bt': 'Bhutan',
  'sl': 'Sierra Leone',
  'kh': 'Cambodia',
  'dz': 'Algeria',
  'ga': 'Gabon',
  // 'taliban': 'Afghanistan', // TODO: to sem sam dodal?
  'am': 'Armenia',
  'lc': 'Saint Lucia',
  'tv': 'Tuvalu',
  'tc': 'Turks and Caicos Islands',
  'gq': 'Equatorial Guinea',
  'sd': 'Sudan',
  'aq': 'Antarctica',
  'st': 'Sao Tome and Principe',
  'si': 'Slovenia',
  'hk': 'Hong Kong',
  // 're': 'RÃ©union',
  're': 'Reunion',
  // 'mf': 'Saint Martin', // french flag
  'lv': 'Latvia',
  'gf': 'French Guiana',
  'pk': 'Pakistan',
  'az': 'Azerbaijan',
  'km': 'Comoros',
  'om': 'Oman',
  'sn': 'Senegal',
  'vi': 'United States Virgin Islands',
  'gh': 'Ghana',
  'cf': 'Central African Republic',
  'gs': 'South Georgia',
  'as': 'American Samoa',
  'il': 'Israel',
  'zw': 'Zimbabwe',
  'bi': 'Burundi',
  'gw': 'Guinea-Bissau',
  'mw': 'Malawi',
  'us': 'United States',
  'pa': 'Panama',
  'mg': 'Madagascar',
  'ge': 'Georgia',
  'pt': 'Portugal',
  'ml': 'Mali',
  'ck': 'Cook Islands',
  'is': 'Iceland',
  'td': 'Chad',
  'tr': 'Turkey',
  'cx': 'Christmas Island',
  'cr': 'Costa Rica',
  'lt': 'Lithuania',
  // 'cc': 'Cocos (Keeling) Islands',
  'cc': 'Cocos Islands',
  'in': 'India',
  'eg': 'Egypt',
  'je': 'Jersey',
  'va': 'Vatican City',
  'za': 'South Africa',
  'jm': 'Jamaica',
  'br': 'Brazil',
  'dk': 'Denmark',
  'be': 'Belgium',
  'py': 'Paraguay',
  'kz': 'Kazakhstan',
  'na': 'Namibia',
  'ci': 'Ivory Coast',
  'mu': 'Mauritius',
  'ps': 'Palestine',
  'me': 'Montenegro',
  'io': 'British Indian Ocean Territory',
  'my': 'Malaysia',
  'dj': 'Djibouti',
  'sb': 'Solomon Islands',
  'gy': 'Guyana',
  'cw': 'Curacao',
  'kg': 'Kyrgyzstan',
  'ph': 'Philippines',
  'pg': 'Papua New Guinea',
  'tt': 'Trinidad and Tobago',
  'ly': 'Libya',
  'aw': 'Aruba',
  'ru': 'Russia',
  'de': 'Germany',
  'gd': 'Grenada',
  'ca': 'Canada',
  'pf': 'French Polynesia',
  'sz': 'Eswatini',
  'ir': 'Iran',
  'jp': 'Japan',
  'cn': 'China',
  // 'bl': 'Saint BarthÃ©lemy',
  'bl': 'Saint Barthelemy',
  'ao': 'Angola',
  'ie': 'Ireland',
  'no': 'Norway',
  'mz': 'Mozambique',
  'jo': 'Jordan',
  'gm': 'Gambia',
  'sg': 'Singapore',
  'sm': 'San Marino',
  'cl': 'Chile',
  'um': 'United States Minor Outlying Islands',
  'bj': 'Benin',
  'lk': 'Sri Lanka',
  'by': 'Belarus',
  'bq': 'Caribbean Netherlands',
  'pe': 'Peru',
  'gg': 'Guernsey',
  // 'ax': 'Ã…land Islands',
  'ax': 'Aland Islands',
  'do': 'Dominican Republic',
  'tk': 'Tokelau',
  'ae': 'United Arab Emirates',
  'au': 'Australia',
  'gt': 'Guatemala',
  'lb': 'Lebanon',
  'lu': 'Luxembourg',
  'al': 'Albania',
  'vu': 'Vanuatu',
  'cd': 'DR Congo',
  'mp': 'Northern Mariana Islands',
  'cz': 'Czechia',
  'it': 'Italy',
  'ug': 'Uganda',
  'ch': 'Switzerland',
  'mx': 'Mexico',
  'tw': 'Taiwan',
  'gn': 'Guinea',
  'fi': 'Finland',
};

const EUROPE = [
  'Albania',
  'Andorra',
  'Austria',
  'Belarus',
  'Belgium',
  'Bosnia and Herzegovina',
  'Bulgaria',
  'Croatia',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Estonia',
  'Faroe Islands',
  'Finland',
  'France',
  'Germany',
  'Gibraltar',
  'Greece',
  'Guernsey',
  'Hungary',
  'Iceland',
  'Ireland',
  'Isle of Man',
  'Italy',
  'Jersey',
  'Kosovo',
  'Latvia',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Malta',
  'Moldova',
  'Monaco',
  'Montenegro',
  'Netherlands',
  'North Macedonia',
  'Norway',
  'Poland',
  'Portugal',
  'Romania',
  'Russia',
  'San Marino',
  'Serbia',
  'Slovakia',
  'Slovenia',
  'Spain',
  // 'Svalbard and Jan Mayen',
  'Sweden',
  'Switzerland',
  'Ukraine',
  'United Kingdom',
  'Vatican City',
  // 'Ã…land Islands',
  'Aland Islands',
];

const ASIA = [
  'Afghanistan',
  'Armenia',
  'Azerbaijan',
  'Bahrain',
  'Bangladesh',
  'Bhutan',
  'Brunei',
  'Cambodia',
  'China',
  'Georgia',
  'Hong Kong',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Israel',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Lebanon',
  'Macau',
  'Malaysia',
  'Maldives',
  'Mongolia',
  'Myanmar',
  'Nepal',
  'North Korea',
  'Oman',
  'Pakistan',
  'Palestine',
  'Philippines',
  'Qatar',
  'Saudi Arabia',
  'Singapore',
  'South Korea',
  'Sri Lanka',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Thailand',
  'Timor-Leste',
  'Turkey',
  'Turkmenistan',
  'United Arab Emirates',
  'Uzbekistan',
  'Vietnam',
  'Yemen',
];

const AFRICA = [
  'Algeria',
  'Angola',
  'Benin',
  'Botswana',
  'British Indian Ocean Territory',
  'Burkina Faso',
  'Burundi',
  'Cameroon',
  'Cape Verde',
  'Central African Republic',
  'Chad',
  'Comoros',
  'DR Congo',
  'Djibouti',
  'Egypt',
  'Equatorial Guinea',
  'Eritrea',
  'Eswatini',
  'Ethiopia',
  'Gabon',
  'Gambia',
  'Ghana',
  'Guinea',
  'Guinea-Bissau',
  'Ivory Coast',
  'Kenya',
  'Lesotho',
  'Liberia',
  'Libya',
  'Madagascar',
  'Malawi',
  'Mali',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Morocco',
  'Mozambique',
  'Namibia',
  'Niger',
  'Nigeria',
  'Republic of the Congo',
  'Rwanda',
  'Reunion',
  // 'Saint Helena, Ascension and Tristan da Cunha',
  'Saint Helena',
  'Senegal',
  'Seychelles',
  'Sierra Leone',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Sudan',
  // 'SÃ£o TomÃ© and PrÃ­ncipe',
  'Sao Tome and Principe',
  'Tanzania',
  'Togo',
  'Tunisia',
  'Uganda',
  'Western Sahara',
  'Zambia',
  'Zimbabwe',
];

const AMERICAS = [
  'Anguilla',
  'Antigua and Barbuda',
  'Argentina',
  'Aruba',
  'Bahamas',
  'Barbados',
  'Belize',
  'Bermuda',
  'Bolivia',
  'Brazil',
  'British Virgin Islands',
  'Canada',
  'Caribbean Netherlands',
  'Cayman Islands',
  'Chile',
  'Colombia',
  'Costa Rica',
  'Cuba',
  'Curacao',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'El Salvador',
  'Falkland Islands',
  'French Guiana',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guatemala',
  'Guyana',
  'Haiti',
  'Honduras',
  'Jamaica',
  'Martinique',
  'Mexico',
  'Montserrat',
  'Nicaragua',
  'Panama',
  'Paraguay',
  'Peru',
  'Puerto Rico',
  // 'Saint BarthÃ©lemy',
  'Saint Barthelemy',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Sint Maarten',
  'Suriname',
  'Trinidad and Tobago',
  'Turks and Caicos Islands',
  'United States',
  'United States Minor Outlying Islands',
  'United States Virgin Islands',
  'Uruguay',
  'Venezuela',
];

const OCEANIA = [
  'American Samoa',
  'Australia',
  'Christmas Island',
  // 'Cocos (Keeling) Islands',
  'Cocos Islands',
  'Cook Islands',
  'Fiji',
  'French Polynesia',
  'Guam',
  'Kiribati',
  'Marshall Islands',
  'Micronesia',
  'Nauru',
  'New Caledonia',
  'New Zealand',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Palau',
  'Papua New Guinea',
  'Pitcairn Islands',
  'Samoa',
  'Solomon Islands',
  'Tokelau',
  'Tonga',
  'Tuvalu',
  'Vanuatu',
  'Wallis and Futuna',
];

const ANTARCTIC = [
  'Antarctica',
  'Bouvet Island',
  'French Southern and Antarctic Lands',
  'Heard Island and McDonald Islands',
  'South Georgia',
];

// const ALL = [...EUROPE, ...ASIA, ...AFRICA, ...AMERICAS, ...OCEANIA, ...ANTARCTIC];

const COUNTRIES = {
  // all: ALL,
  europe: EUROPE,
  asia: ASIA,
  africa: AFRICA,
  americas: AMERICAS,
  oceania: OCEANIA,
  antarctic: ANTARCTIC,
};